caKeyLength: 4096
certKeyLength: 3072
city: Moncton
country: CA
domain: at.home
hashAlgorithm: sha256
organization: "My Family"
organizationalUnit: "Home"
state: NB

rootAuthority:
  dir: "/Users/sean/.ca/root"
  name: My Family Root CA
  contact: support@at.home
  daysValid: 36500

intermediateAuthority:
  dir: "/Users/sean/.ca/intermediate"
  name: My Family Issuing CA
  contact: support@at.home
  daysValid: 3650
